version: 3

jobs:
  build:
# enable once needed
#    docker:
#      - image: mongo:4.2-bionic
#        environment:
#          MONGO_INITDB_ROOT_USERNAME: mongoAdmin # These are dummy credentials for CI checks only
#          MONGO_INITDB_ROOT_PASSWORD: Password1
#        command: [mongod, --replSet, rs0]
    docker:
      - image: circleci/python:3.6.2
    steps:
      - checkout
      - add_ssh_keys

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "setup.py" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: 'Create virtual env'
          command: |
            make create_venv

      - run:
          name: 'Setup virtual env'
          command: |
            source ./venv/bin/activate
            make upgrade_pip install_dep

      - run:
          name: 'Check dependencies'
          command: |
            source ./virtualenvs/tap-mongodb/bin/activate
            make check_dep

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.py" }}

      - run:
          name: 'Pylinting'
          command: |
            source ./virtualenvs/tap-mongodb/bin/activate
            make pylint

      - run:
          name: 'Test'
          command: |
            source ./virtualenvs/tap-mongodb/bin/activate
            make test

workflows:
  version: 2
  commit:
    jobs:
      - build
